name: Run PowerShell Script

on: 
  workflow_dispatch:  # Allow manual triggers

jobs:
  run-script:
    runs-on: windows-latest  # Use Windows for PowerShell
    environment: hari_personal
    
    env:
      ACTIONS_STEP_DEBUG: true  # Enable step debugging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print environment variables
        run: |
          echo "KOBO_TOKEN: $KOBO_TOKEN"
          echo "ASSET_ID_OP7PLANT_MONITORING: $ASSET_ID_OP7PLANT_MONITORING"
          echo "KOBO_URL_BASE: $KOBO_URL_BASE"

      - name: Run PowerShell script
        env:
          KOBO_TOKEN: ${{ secrets.KOBO_TOKEN }}
          ASSET_ID_OP7PLANT_MONITORING: ${{ secrets.ASSET_ID_OP7PLANT_MONITORING }}
          KOBO_URL_BASE: ${{ secrets.KOBO_URL_BASE }}
        run: |
          pwsh -File get_op7planting_data.ps1

      - name: Upload log file
        uses: actions/upload-artifact@v3
        with:
          name: log-file
          path: OP7PlantingData\OP7Planting_log.txt  # Adjust if necessary
